"""Generate a signed PDF version of the CAB report.

Uses fpdf2 (pure Python, no external binary dependencies) to produce a
PDF that embeds a SHA-256 content hash in the document metadata.  This
makes the PDF tamper-evident: any edit to the content changes the hash.

The PDF is NOT digitally signed with a certificate (that would require
a PKI infrastructure).  Instead it uses a content-integrity approach:
the SHA-256 of the Markdown source is embedded as a PDF metadata field
and printed in the document footer, so a reviewer can verify by
re-generating the report from the same session data and comparing
digests.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from pathlib import Path

from fpdf import FPDF

from .execution import TestResult
from .report import cab_report

# Unicode symbols used in the report → ASCII-safe replacements for Latin-1 fonts.
_UNICODE_REPLACEMENTS = {
    "\u2014": "--",      # em dash
    "\u2013": "-",       # en dash
    "\u2018": "'",       # left single quote
    "\u2019": "'",       # right single quote
    "\u201c": '"',       # left double quote
    "\u201d": '"',       # right double quote
    "\u2026": "...",     # ellipsis
    "\u2192": "->",      # right arrow
    "\u2190": "<-",      # left arrow
    "\u2260": "!=",      # not equal
    "\u2264": "<=",      # less than or equal
    "\u2265": ">=",      # greater than or equal
    "\u2713": "[v]",     # check mark
    "\u2714": "[v]",     # heavy check mark
    "\u2715": "[x]",     # cross mark
    "\u2716": "[x]",     # heavy cross mark
    "\u2717": "[x]",     # ballot x
    "\u2718": "[x]",     # heavy ballot x
    "\u2022": "*",       # bullet
    "\u00b7": "*",       # middle dot
    "\u2605": "*",       # star
    "\u2606": "*",       # white star
    "\u2610": "[ ]",     # ballot box
    "\u2611": "[v]",     # ballot box with check
    "\u2612": "[x]",     # ballot box with X
    "\u2705": "[OK]",    # white heavy check mark
    "\u274c": "[FAIL]",  # cross mark
    "\u26d4": "[BLOCK]", # no entry
    "\ud83d\udfe2": "[OK]",    # green circle
    "\ud83d\udd34": "[FAIL]",  # red circle
    "\ud83d\udfe1": "[REVIEW]", # yellow circle
    "\ud83d\udfe0": "[!]",     # orange circle
    "\u26a0": "[!]",     # warning sign
    "\u2139": "[i]",     # information
}


def _sanitize(text: str) -> str:
    """Replace Unicode symbols with ASCII equivalents for Latin-1 fonts."""
    for char, replacement in _UNICODE_REPLACEMENTS.items():
        text = text.replace(char, replacement)
    # Catch any remaining non-Latin-1 characters
    return text.encode("latin-1", "replace").decode("latin-1")


class _CabPDF(FPDF):
    """Custom PDF with header/footer for the CAB report."""

    def __init__(self, meta: dict, content_hash: str) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self._meta = meta
        self._content_hash = content_hash
        self.set_auto_page_break(auto=True, margin=20)

    def header(self) -> None:
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(100, 100, 100)
        env = _sanitize(self._meta.get("environment", "?"))
        self.cell(0, 6, f"DCC Enablement Configuration - CAB Report [{env}]", align="L")
        self.cell(0, 6, f"SHA-256: {self._content_hash[:16]}...", align="R", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self) -> None:
        self.set_y(-18)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(120, 120, 120)
        self.cell(0, 4, f"Content SHA-256: {self._content_hash}", align="L", new_x="LMARGIN", new_y="NEXT")
        self.cell(
            0, 4,
            f"Generated by DCC Test Console | Page {self.page_no()}/{{nb}}",
            align="C",
        )


def _safe_cell(pdf: _CabPDF, height: float, text: str) -> None:
    """Write text via multi_cell, truncating if it would overflow the page width."""
    usable = pdf.w - pdf.l_margin - pdf.r_margin - (pdf.x - pdf.l_margin)
    if usable < 10:
        pdf.set_x(pdf.l_margin)
        usable = pdf.w - pdf.l_margin - pdf.r_margin
    # Truncate text that would still overflow at the smallest font size
    max_chars = int(usable / (pdf.font_size * 0.25))
    if len(text) > max_chars > 0:
        text = text[:max_chars] + "..."
    pdf.multi_cell(0, height, text)


def _render_markdown_to_pdf(pdf: _CabPDF, markdown: str) -> None:
    """Simple Markdown-to-PDF renderer for the structured CAB report."""
    for line in markdown.split("\n"):
        stripped = _sanitize(line.strip())

        # Headings
        if stripped.startswith("# ") and not stripped.startswith("## "):
            pdf.set_font("Helvetica", "B", 16)
            pdf.set_text_color(0, 0, 0)
            pdf.ln(4)
            _safe_cell(pdf, 8, stripped.lstrip("# "))
            pdf.ln(2)
        elif stripped.startswith("## "):
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(30, 60, 120)
            pdf.ln(3)
            _safe_cell(pdf, 7, stripped.lstrip("# "))
            pdf.ln(1)
        elif stripped.startswith("### "):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.ln(2)
            _safe_cell(pdf, 6, stripped.lstrip("# "))
            pdf.ln(1)

        # Table rows
        elif stripped.startswith("|") and "---" not in stripped:
            pdf.set_font("Courier", "", 6)
            pdf.set_text_color(0, 0, 0)
            text = stripped.replace("\\|", "|")
            _safe_cell(pdf, 3.5, text)

        # Code blocks
        elif stripped.startswith("```"):
            pass  # skip fences
        elif stripped.startswith("EXEC ") or stripped.startswith("SELECT "):
            pdf.set_font("Courier", "", 6)
            pdf.set_text_color(0, 80, 0)
            _safe_cell(pdf, 3.5, stripped)

        # Blockquotes
        elif stripped.startswith(">"):
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(80, 80, 80)
            _safe_cell(pdf, 5, stripped.lstrip("> "))

        # Bullet points
        elif stripped.startswith("- "):
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(0, 0, 0)
            _safe_cell(pdf, 5, f"  {stripped}")

        # Horizontal rule
        elif stripped == "---":
            pdf.ln(2)
            y = pdf.get_y()
            pdf.line(10, y, 200, y)
            pdf.ln(2)

        # Italic notes
        elif stripped.startswith("_") and stripped.endswith("_"):
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(100, 100, 100)
            _safe_cell(pdf, 5, stripped.strip("_"))

        # Bold text
        elif stripped.startswith("**") and stripped.endswith("**"):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(0, 0, 0)
            _safe_cell(pdf, 5, stripped.strip("*"))

        # Regular text
        elif stripped:
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(0, 0, 0)
            _safe_cell(pdf, 5, stripped)

        # Empty lines
        else:
            pdf.ln(2)


def generate_cab_pdf(
    results: list[TestResult],
    meta: dict | None = None,
    rollback_evidence: list | None = None,
    output_path: str | Path | None = None,
) -> tuple[bytes, str]:
    """Generate a signed PDF CAB report.

    Returns ``(pdf_bytes, content_sha256)``.  If *output_path* is given, the
    PDF is also written to disk.
    """
    meta = meta or {}
    if "generated_at" not in meta:
        meta["generated_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")

    # Generate Markdown and compute its hash
    markdown = cab_report(results, meta, rollback_evidence)
    content_hash = hashlib.sha256(markdown.encode("utf-8")).hexdigest()
    meta["content_hash"] = content_hash

    # Regenerate with hash embedded
    markdown = cab_report(results, meta, rollback_evidence)

    # Build PDF
    pdf = _CabPDF(meta, content_hash)
    pdf.alias_nb_pages()
    pdf.set_title("DCC CAB Validation Report")
    pdf.set_author(f"DCC Test Console ({meta.get('login', 'unknown')})")
    pdf.set_subject(f"Environment: {meta.get('environment', '?')}")
    pdf.set_keywords(f"SHA256:{content_hash}")
    pdf.set_creator("dcc_console/pdf_report.py")

    pdf.add_page()

    # Title page info
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 12, "DCC Enablement Configuration", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 14)
    pdf.cell(0, 10, "CAB Validation Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(60, 60, 60)
    env_line = _sanitize(f"Environment: {meta.get('environment', '?')}    Server: {meta.get('server', '?')}")
    login_line = _sanitize(f"Generated: {meta.get('generated_at', '?')}    Login: {meta.get('login', '?')}")
    pdf.cell(0, 6, env_line, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, login_line, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Integrity box
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Courier", "B", 8)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, f"  Report integrity SHA-256: {content_hash}", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Render the full markdown report
    _render_markdown_to_pdf(pdf, markdown)

    pdf_bytes = pdf.output()
    if output_path:
        Path(output_path).write_bytes(pdf_bytes)

    return pdf_bytes, content_hash


__all__ = ["generate_cab_pdf"]
