-- =====================================================================
-- DCC Remediation schema for DEV_CORE_AAB.DCC_REMEDIATION (shared log: DEV_CORE_AAB.DCC_REMEDIATION)
-- GENERATED from src/dcc_console/remediation/ddl.py (build_initialise_statements()).
-- Do not hand-edit; change the builder and regenerate. Idempotent, safe to re-run.
-- The app's "Initialise / verify my schema" button runs exactly these statements
-- for the connected user's own schema (+ the shared fix-log schema).
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS DEV_CORE_AAB.DCC_REMEDIATION;

CREATE TABLE IF NOT EXISTS DEV_CORE_AAB.DCC_REMEDIATION.APP_FIX_LOG (
    FIX_ID               NUMBER       AUTOINCREMENT START 1 INCREMENT 1,
    CORRELATION_ID       VARCHAR(64)  NOT NULL,
    APPLIED_AT           TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    APPLIED_BY           VARCHAR(150) NOT NULL,
    MODE                 VARCHAR(12)  NOT NULL,
    ENVIRONMENT          VARCHAR(20)  NOT NULL,
    SERVER               VARCHAR(200) NOT NULL,
    DATABASE_NAME        VARCHAR(100) NOT NULL,
    FIX_BIT              NUMBER(4,0)  NOT NULL,
    CHECK_COLUMN         VARCHAR(80),
    FLAG_NAME            VARCHAR(120),
    TARGET_ID_KIND       VARCHAR(30)  NOT NULL,
    TARGET_IDENTIFIER    VARCHAR(100) NOT NULL,
    INSTANCE_IDENTIFIER  VARCHAR(100),
    TERMINAL_IDENTIFIER  VARCHAR(100),
    LOCATION_NO          VARCHAR(50),
    VALUE_SENT           VARCHAR(120),
    STATE_BEFORE         VARCHAR,
    STATE_AFTER          VARCHAR,
    VERIFIED             BOOLEAN,
    ROLLBACK_SCRIPT      VARCHAR,
    OUTCOME              VARCHAR(30)  NOT NULL,
    ERROR                VARCHAR,
    BANK_MERCHANT_ID     VARCHAR(50),
    MERCHANT_NAME        VARCHAR(250),
    CUSTOMER_NAME        VARCHAR(250),
    COUNTRY_NAME         VARCHAR(100),
    REGION               VARCHAR(100),
    INDUSTRY_NAME        VARCHAR(100),
    ACQUIRER_NAME        VARCHAR(250),
    TERMINAL_BRAND_NAME  VARCHAR(100),
    TERMINAL_MODEL_NAME  VARCHAR(200),
    SQL_LOGIN            VARCHAR(128),
    NOTES                VARCHAR(1000),
    CHANGE_REF           VARCHAR(120),
    PRIMARY KEY (FIX_ID)
);

ALTER TABLE DEV_CORE_AAB.DCC_REMEDIATION.APP_FIX_LOG ADD COLUMN IF NOT EXISTS SQL_LOGIN VARCHAR(128);

ALTER TABLE DEV_CORE_AAB.DCC_REMEDIATION.APP_FIX_LOG ADD COLUMN IF NOT EXISTS NOTES VARCHAR(1000);

ALTER TABLE DEV_CORE_AAB.DCC_REMEDIATION.APP_FIX_LOG ADD COLUMN IF NOT EXISTS CHANGE_REF VARCHAR(120);

CREATE TABLE IF NOT EXISTS DEV_CORE_AAB.DCC_REMEDIATION.FIX_OPERATORS (
    USER_NAME   VARCHAR(150)  NOT NULL PRIMARY KEY,
    ACTIVE      BOOLEAN       NOT NULL DEFAULT TRUE,
    CAN_PROD    BOOLEAN       NOT NULL DEFAULT FALSE,
    ADDED_BY    VARCHAR(150)  NOT NULL DEFAULT CURRENT_USER(),
    ADDED_AT    TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    NOTES       VARCHAR(500)
);

ALTER TABLE DEV_CORE_AAB.DCC_REMEDIATION.FIX_OPERATORS ADD COLUMN IF NOT EXISTS CAN_PROD BOOLEAN;

INSERT INTO DEV_CORE_AAB.DCC_REMEDIATION.FIX_OPERATORS (USER_NAME, NOTES)
SELECT CURRENT_USER(), 'First operator (initialised the shared fix log)'
WHERE NOT EXISTS (SELECT 1 FROM DEV_CORE_AAB.DCC_REMEDIATION.FIX_OPERATORS);

CREATE TABLE IF NOT EXISTS DEV_CORE_AAB.DCC_REMEDIATION.DCC_FIX_REGISTRY (
    ENVIRONMENT          VARCHAR(20)  NOT NULL,
    TERMINAL_IDENTIFIER  VARCHAR(100) NOT NULL,
    CHECK_COLUMN         VARCHAR(80)  NOT NULL,
    INSTANCE_IDENTIFIER  VARCHAR(100),
    LOCATION_NO          VARCHAR(50),
    FIX_BIT              NUMBER(4,0),
    FLAG_NAME            VARCHAR(120),
    VALUE_SENT           VARCHAR(120),
    TARGET_ID_KIND       VARCHAR(30),
    TARGET_IDENTIFIER    VARCHAR(100),
    CORRELATION_ID       VARCHAR(64),
    CHANGE_REF           VARCHAR(120),
    RESOLUTION           VARCHAR(20)  NOT NULL,
    STATUS               VARCHAR(20)  NOT NULL DEFAULT 'FIXED',
    SP_ROLLBACK_SCRIPT   VARCHAR,
    FIXED_BY             VARCHAR(150),
    FIXED_AT             TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    FIXED_AT_UTC         TIMESTAMP_NTZ NOT NULL,
    PRIMARY KEY (ENVIRONMENT, TERMINAL_IDENTIFIER, CHECK_COLUMN)
);

MERGE INTO DEV_CORE_AAB.DCC_REMEDIATION.DCC_FIX_REGISTRY tgt
USING (
    WITH latest AS (
        SELECT TERMINAL_IDENTIFIER, CHECK_COLUMN, INSTANCE_IDENTIFIER, LOCATION_NO,
               FIX_BIT, FLAG_NAME, VALUE_SENT, TARGET_ID_KIND, TARGET_IDENTIFIER,
               CORRELATION_ID, APPLIED_BY, ROLLBACK_SCRIPT, OUTCOME, VERIFIED, APPLIED_AT
        FROM DEV_CORE_AAB.DCC_REMEDIATION.APP_FIX_LOG
        WHERE ENVIRONMENT = 'PROD' AND MODE = 'LIVE' AND CHECK_COLUMN IS NOT NULL
          AND OUTCOME IN ('APPLIED', 'SKIPPED_ALREADY_OK', 'ROLLED_BACK')
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY TERMINAL_IDENTIFIER, CHECK_COLUMN ORDER BY APPLIED_AT DESC, FIX_ID DESC
        ) = 1
    )
    SELECT 'PROD' AS ENVIRONMENT, TERMINAL_IDENTIFIER, CHECK_COLUMN, INSTANCE_IDENTIFIER,
           LOCATION_NO, FIX_BIT, FLAG_NAME, VALUE_SENT, TARGET_ID_KIND, TARGET_IDENTIFIER,
           CORRELATION_ID, NULL AS CHANGE_REF,
           IFF(OUTCOME = 'APPLIED', 'APPLIED', 'ALREADY_OK') AS RESOLUTION,
           ROLLBACK_SCRIPT AS SP_ROLLBACK_SCRIPT, APPLIED_BY AS FIXED_BY,
           CONVERT_TIMEZONE('UTC', APPLIED_AT)::TIMESTAMP_NTZ AS FIXED_AT_UTC
    FROM latest
    WHERE OUTCOME IN ('APPLIED', 'SKIPPED_ALREADY_OK') AND VERIFIED = TRUE
) src
ON tgt.ENVIRONMENT = src.ENVIRONMENT
   AND tgt.TERMINAL_IDENTIFIER = src.TERMINAL_IDENTIFIER
   AND tgt.CHECK_COLUMN = src.CHECK_COLUMN
WHEN NOT MATCHED THEN INSERT (
    ENVIRONMENT, TERMINAL_IDENTIFIER, CHECK_COLUMN, INSTANCE_IDENTIFIER, LOCATION_NO,
    FIX_BIT, FLAG_NAME, VALUE_SENT, TARGET_ID_KIND, TARGET_IDENTIFIER, CORRELATION_ID,
    CHANGE_REF, RESOLUTION, SP_ROLLBACK_SCRIPT, FIXED_BY, STATUS, FIXED_AT, FIXED_AT_UTC
) VALUES (
    src.ENVIRONMENT, src.TERMINAL_IDENTIFIER, src.CHECK_COLUMN, src.INSTANCE_IDENTIFIER,
    src.LOCATION_NO, src.FIX_BIT, src.FLAG_NAME, src.VALUE_SENT, src.TARGET_ID_KIND,
    src.TARGET_IDENTIFIER, src.CORRELATION_ID, src.CHANGE_REF, src.RESOLUTION,
    src.SP_ROLLBACK_SCRIPT, src.FIXED_BY, 'FIXED', CURRENT_TIMESTAMP(), src.FIXED_AT_UTC
);

CREATE SCHEMA IF NOT EXISTS DEV_CORE_AAB.DCC_REMEDIATION;

CREATE TABLE IF NOT EXISTS DEV_CORE_AAB.DCC_REMEDIATION.FLAG_REFERENCE (
    CHECK_COLUMN     VARCHAR(80)  NOT NULL PRIMARY KEY,
    FLAG_NAME        VARCHAR(120) NOT NULL,
    FLAG_TYPE        VARCHAR(30)  NOT NULL,
    FIX_BIT          NUMBER(4,0),
    TARGET_ID_KIND   VARCHAR(30),
    FIX_VALUE        VARCHAR(120),
    SP_COLUMN        VARCHAR(60),
    FIXABLE          BOOLEAN      NOT NULL DEFAULT FALSE,
    NOTES            VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS DEV_CORE_AAB.DCC_REMEDIATION.HEALTH_DAILY_SNAPSHOT (
    SNAPSHOT_DATE        DATE NOT NULL,
    TERMINAL_IDENTIFIER  VARCHAR(100) NOT NULL,
    INSTANCE_IDENTIFIER  VARCHAR(100),
    LOCATION_NO          VARCHAR(50),
    COUNTRY_NAME         VARCHAR(100),
    REGION               VARCHAR(100),
    INDUSTRY_NAME        VARCHAR(100),
    BANK_MERCHANT_ID     VARCHAR(50),
    MERCHANT_NAME        VARCHAR(250),
    CUSTOMER_NAME        VARCHAR(250),
    ACQUIRER_NAME        VARCHAR(250),
    LOCATION_NAME        VARCHAR(500),
    TERMINAL_BRAND_NAME  VARCHAR(100),
    TERMINAL_MODEL_NAME  VARCHAR(200),
    FIRMWARE_VERSION     VARCHAR(200),
    LOCATION_DCCENABLED_CHECK_C INTEGER,
    HANDLER_DCCENABLE_CHECK_O INTEGER,
    HANDLER_DCCENABLECOMPLETION_CHECK_O INTEGER,
    HANDLER_DCCENABLEAUTH_CHECK_O INTEGER,
    HANDLER_DCCENABLENFC_CHECK_O INTEGER,
    HANDLER_DCCENABLENFCSINGLETAP_CHECK_O INTEGER,
    DCCFLAGSENABLED_CHECK_C INTEGER,
    DCCXPRESSCO_CHECK_O INTEGER,
    DCCXPRESSCODT_CHECK_O INTEGER,
    DCCXPRESSCOFALLBACK_CHECK_O INTEGER,
    DCCMERCHANT_NO_CHECK_O INTEGER,
    FIRMWARE_VERSION_CHECK INTEGER,
    PRINTOUTTYPETEMPLATEDCC_CHECK_C INTEGER,
    CONFIGDOWNLOAD_VERSION_CHECK_C INTEGER,
    IS_DCC_BROKEN        BOOLEAN      NOT NULL,
    SOURCE_LAST_ALTERED  TIMESTAMP_NTZ,
    CAPTURED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SNAPSHOT_DATE, TERMINAL_IDENTIFIER)
)
CLUSTER BY (SNAPSHOT_DATE);

CREATE OR REPLACE VIEW DEV_CORE_AAB.DCC_REMEDIATION.V_CURRENT_BROKEN AS
WITH latest AS (
    -- Only the most recent load: a terminal repaired since an earlier snapshot has no
    -- row in the newest one and must drop out rather than resurface from an old date.
    SELECT * FROM DEV_CORE_AAB.DCC_REMEDIATION.HEALTH_DAILY_SNAPSHOT
    WHERE SNAPSHOT_DATE = (SELECT MAX(SNAPSHOT_DATE) FROM DEV_CORE_AAB.DCC_REMEDIATION.HEALTH_DAILY_SNAPSHOT)
),
fixed AS (
    -- Durable registry of verified PROD fixes (DCC_FIX_REGISTRY): a row
    -- is written when a live fix is verified by a fresh SQL-Server read (or a live
    -- pre-check proves the check already satisfied) and DELETED when a rollback is
    -- confirmed, so a later rollback re-opens the check. It survives the daily refresh,
    -- and UAT/DEV rehearsals never hide PROD work (only
    -- ENVIRONMENT = 'PROD' rows count). Only fixes newer than the source
    -- load the snapshot was built from count, so a terminal re-broken in a later load
    -- resurfaces (FIXED_AT_UTC and SOURCE_LAST_ALTERED are both UTC).
    SELECT l.TERMINAL_IDENTIFIER,
           ARRAY_AGG(DISTINCT g.CHECK_COLUMN) AS FIXED_CHECKS,
           MAX(g.FIXED_AT_UTC) AS LAST_FIX_AT_UTC
    FROM latest l
    JOIN DEV_CORE_AAB.DCC_REMEDIATION.DCC_FIX_REGISTRY g
      ON g.TERMINAL_IDENTIFIER = l.TERMINAL_IDENTIFIER
     AND g.ENVIRONMENT = 'PROD' AND g.STATUS = 'FIXED'
     AND g.FIXED_AT_UTC > l.SOURCE_LAST_ALTERED
    GROUP BY l.TERMINAL_IDENTIFIER
),
joined AS (
    SELECT l.*,
           COALESCE(f.FIXED_CHECKS, ARRAY_CONSTRUCT()) AS FIXED_CHECKS,
           f.LAST_FIX_AT_UTC
    FROM latest l
    LEFT JOIN fixed f ON f.TERMINAL_IDENTIFIER = l.TERMINAL_IDENTIFIER
),
scored AS (
    SELECT *,
        IFF(HANDLER_DCCENABLE_CHECK_O = 1 AND NOT ARRAY_CONTAINS('HANDLER_DCCENABLE_CHECK_O'::VARIANT, FIXED_CHECKS), 1, 0)
        + IFF(HANDLER_DCCENABLECOMPLETION_CHECK_O = 1 AND NOT ARRAY_CONTAINS('HANDLER_DCCENABLECOMPLETION_CHECK_O'::VARIANT, FIXED_CHECKS), 1, 0)
        + IFF(HANDLER_DCCENABLEAUTH_CHECK_O = 1 AND NOT ARRAY_CONTAINS('HANDLER_DCCENABLEAUTH_CHECK_O'::VARIANT, FIXED_CHECKS), 1, 0)
        + IFF(HANDLER_DCCENABLENFC_CHECK_O = 1 AND NOT ARRAY_CONTAINS('HANDLER_DCCENABLENFC_CHECK_O'::VARIANT, FIXED_CHECKS), 1, 0)
        + IFF(HANDLER_DCCENABLENFCSINGLETAP_CHECK_O = 1 AND NOT ARRAY_CONTAINS('HANDLER_DCCENABLENFCSINGLETAP_CHECK_O'::VARIANT, FIXED_CHECKS), 1, 0)
        + IFF(DCCXPRESSCO_CHECK_O = 1 AND NOT ARRAY_CONTAINS('DCCXPRESSCO_CHECK_O'::VARIANT, FIXED_CHECKS), 1, 0)
        + IFF(DCCXPRESSCODT_CHECK_O = 1 AND NOT ARRAY_CONTAINS('DCCXPRESSCODT_CHECK_O'::VARIANT, FIXED_CHECKS), 1, 0)
        + IFF(DCCXPRESSCOFALLBACK_CHECK_O = 1 AND NOT ARRAY_CONTAINS('DCCXPRESSCOFALLBACK_CHECK_O'::VARIANT, FIXED_CHECKS), 1, 0)
        + IFF(PRINTOUTTYPETEMPLATEDCC_CHECK_C = 1 AND NOT ARRAY_CONTAINS('PRINTOUTTYPETEMPLATEDCC_CHECK_C'::VARIANT, FIXED_CHECKS), 1, 0)
        + IFF(CONFIGDOWNLOAD_VERSION_CHECK_C = 1 AND NOT ARRAY_CONTAINS('CONFIGDOWNLOAD_VERSION_CHECK_C'::VARIANT, FIXED_CHECKS), 1, 0) AS OPEN_FIXABLE_CHECKS
    FROM joined
)
-- AWAITING_REFRESH: something was resolved and no fixable check is still open, so the
-- next load should clear it. Terminals whose only broken checks are not fixable here
-- stay ACTIONABLE (visible with "Fixable checks only" switched off).
SELECT *,
    CASE WHEN ARRAY_SIZE(FIXED_CHECKS) > 0 AND OPEN_FIXABLE_CHECKS = 0
         THEN 'AWAITING_REFRESH' ELSE 'ACTIONABLE' END AS REMEDIATION_STATE
FROM scored;

CREATE OR REPLACE VIEW DEV_CORE_AAB.DCC_REMEDIATION.V_FIX_HISTORY AS
SELECT
    APPLIED_AT, APPLIED_AT::DATE AS FIX_DATE, CORRELATION_ID,
    APPLIED_BY, SQL_LOGIN, MODE, ENVIRONMENT, FIX_BIT, CHECK_COLUMN, FLAG_NAME,
    TARGET_ID_KIND, TARGET_IDENTIFIER, TERMINAL_IDENTIFIER, VALUE_SENT, VERIFIED,
    OUTCOME, ERROR, NOTES,
    BANK_MERCHANT_ID, MERCHANT_NAME, CUSTOMER_NAME, COUNTRY_NAME, REGION,
    INDUSTRY_NAME, ACQUIRER_NAME, TERMINAL_BRAND_NAME, TERMINAL_MODEL_NAME
FROM DEV_CORE_AAB.DCC_REMEDIATION.APP_FIX_LOG;

CREATE OR REPLACE VIEW DEV_CORE_AAB.DCC_REMEDIATION.V_REMEDIATION_KPIS AS
SELECT
    (SELECT COUNT(*) FROM DEV_CORE_AAB.DCC_REMEDIATION.V_CURRENT_BROKEN
        WHERE REMEDIATION_STATE = 'ACTIONABLE')                       AS BROKEN_ACTIONABLE,
    (SELECT COUNT(*) FROM DEV_CORE_AAB.DCC_REMEDIATION.V_CURRENT_BROKEN
        WHERE REMEDIATION_STATE = 'AWAITING_REFRESH')                 AS AWAITING_REFRESH,
    -- One CORRELATION_ID per procedure call; one row per terminal it covered.
    (SELECT COUNT(DISTINCT CORRELATION_ID) FROM DEV_CORE_AAB.DCC_REMEDIATION.APP_FIX_LOG
        WHERE OUTCOME = 'APPLIED' AND MODE = 'LIVE' AND ENVIRONMENT = 'PROD')                              AS TOTAL_LIVE_FIXES,
    (SELECT COUNT(DISTINCT TERMINAL_IDENTIFIER) FROM DEV_CORE_AAB.DCC_REMEDIATION.APP_FIX_LOG
        WHERE OUTCOME = 'APPLIED' AND MODE = 'LIVE' AND ENVIRONMENT = 'PROD')                              AS UNIQUE_TERMINALS_FIXED,
    (SELECT COUNT(DISTINCT CORRELATION_ID) FROM DEV_CORE_AAB.DCC_REMEDIATION.APP_FIX_LOG
        WHERE OUTCOME = 'APPLIED' AND MODE = 'LIVE' AND NOT ENVIRONMENT = 'PROD')                          AS REHEARSAL_FIXES,
    (SELECT COUNT(*) FROM DEV_CORE_AAB.DCC_REMEDIATION.DCC_FIX_REGISTRY
        WHERE ENVIRONMENT = 'PROD' AND STATUS = 'FIXED') AS REGISTERED_FIXES,
    (SELECT MAX(SNAPSHOT_DATE) FROM DEV_CORE_AAB.DCC_REMEDIATION.HEALTH_DAILY_SNAPSHOT)            AS LATEST_SNAPSHOT_DATE;
