-- =====================================================================
-- Refresh DEV_CORE_AAB.DCC_REMEDIATION.HEALTH_DAILY_SNAPSHOT
-- GENERATED from src/dcc_console/remediation/snapshot.py (build_refresh_merge()).
-- Do not hand-edit; change the builder and regenerate. Idempotent upsert.
-- =====================================================================

MERGE INTO DEV_CORE_AAB.DCC_REMEDIATION.HEALTH_DAILY_SNAPSHOT tgt
USING (
    SELECT
        CURRENT_DATE() AS SNAPSHOT_DATE,
        TERMINAL_IDENTIFIER,
        MAX(INSTANCE_IDENTIFIER) AS INSTANCE_IDENTIFIER,
        MAX(LOCATION_NO) AS LOCATION_NO,
        MAX(COUNTRY_NAME) AS COUNTRY_NAME,
        MAX(REGION) AS REGION,
        MAX(INDUSTRY_NAME) AS INDUSTRY_NAME,
        MAX(BANK_MERCHANT_ID) AS BANK_MERCHANT_ID,
        MAX(MERCHANT_NAME) AS MERCHANT_NAME,
        MAX(CUSTOMER_NAME) AS CUSTOMER_NAME,
        MAX(ACQUIRER_NAME) AS ACQUIRER_NAME,
        MAX(LOCATION_NAME) AS LOCATION_NAME,
        MAX(TERMINAL_BRAND_NAME) AS TERMINAL_BRAND_NAME,
        MAX(TERMINAL_MODEL_NAME) AS TERMINAL_MODEL_NAME,
        MAX(FIRMWARE_VERSION) AS FIRMWARE_VERSION,
        MAX(IFF(LOCATION_DCCENABLED_BASE = 1 AND COALESCE(LOCATION_DCCENABLED_CHECK_C, 1) = 1, 1, 0)) AS LOCATION_DCCENABLED_CHECK_C,
        MAX(IFF(HANDLER_DCCENABLE_BASE = 1 AND COALESCE(HANDLER_DCCENABLE_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLE_CHECK_O,
        MAX(IFF(HANDLER_DCCENABLECOMPLETION_BASE = 1 AND COALESCE(HANDLER_DCCENABLECOMPLETION_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLECOMPLETION_CHECK_O,
        MAX(IFF(HANDLER_DCCENABLEAUTH_BASE = 1 AND COALESCE(HANDLER_DCCENABLEAUTH_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLEAUTH_CHECK_O,
        MAX(IFF(HANDLER_DCCENABLENFC_BASE = 1 AND COALESCE(HANDLER_DCCENABLENFC_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLENFC_CHECK_O,
        MAX(IFF(HANDLER_DCCENABLENFCSINGLETAP_BASE = 1 AND COALESCE(HANDLER_DCCENABLENFCSINGLETAP_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLENFCSINGLETAP_CHECK_O,
        MAX(IFF(DCCFLAGSENABLED_BASE = 1 AND COALESCE(DCCFLAGSENABLED_CHECK_C, 1) = 1, 1, 0)) AS DCCFLAGSENABLED_CHECK_C,
        MAX(IFF(DCCXPRESSCO_BASE = 1 AND COALESCE(DCCXPRESSCO_CHECK_O, 1) = 1, 1, 0)) AS DCCXPRESSCO_CHECK_O,
        MAX(IFF(DCCXPRESSCODT_BASE = 1 AND COALESCE(DCCXPRESSCODT_CHECK_O, 1) = 1, 1, 0)) AS DCCXPRESSCODT_CHECK_O,
        MAX(IFF(DCCXPRESSCOFALLBACK_BASE = 1 AND COALESCE(DCCXPRESSCOFALLBACK_CHECK_O, 1) = 1, 1, 0)) AS DCCXPRESSCOFALLBACK_CHECK_O,
        MAX(IFF(DCCMERCHANT_NO_BASE = 1 AND COALESCE(DCCMERCHANT_NO_CHECK_O, 1) = 1, 1, 0)) AS DCCMERCHANT_NO_CHECK_O,
        MAX(IFF(FIRMWARE_VERSION_BASE = 1 AND COALESCE(FIRMWARE_VERSION_CHECK, 1) = 1, 1, 0)) AS FIRMWARE_VERSION_CHECK,
        MAX(IFF(PRINTOUTTYPETEMPLATEDCC_BASE = 1 AND COALESCE(PRINTOUTTYPETEMPLATEDCC_CHECK_C, 1) = 1, 1, 0)) AS PRINTOUTTYPETEMPLATEDCC_CHECK_C,
        MAX(IFF(CONFIGDOWNLOAD_VERSION_CHECK_BASE = 1 AND COALESCE(CONFIGDOWNLOAD_VERSION_CHECK_C, 1) = 1, 1, 0)) AS CONFIGDOWNLOAD_VERSION_CHECK_C,
        (SELECT LAST_ALTERED::TIMESTAMP_NTZ FROM PROD_PRESENTATION.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='CORTEX' AND TABLE_NAME='CORTEX_TERMINAL_MAINTENANCE') AS SOURCE_LAST_ALTERED
    FROM PROD_PRESENTATION.CORTEX.CORTEX_TERMINAL_MAINTENANCE
    WHERE TERMINAL_IDENTIFIER IS NOT NULL
      AND (
           (LOCATION_DCCENABLED_BASE = 1 AND COALESCE(LOCATION_DCCENABLED_CHECK_C, 1) = 1)
           OR (HANDLER_DCCENABLE_BASE = 1 AND COALESCE(HANDLER_DCCENABLE_CHECK_O, 1) = 1)
           OR (HANDLER_DCCENABLECOMPLETION_BASE = 1 AND COALESCE(HANDLER_DCCENABLECOMPLETION_CHECK_O, 1) = 1)
           OR (HANDLER_DCCENABLEAUTH_BASE = 1 AND COALESCE(HANDLER_DCCENABLEAUTH_CHECK_O, 1) = 1)
           OR (HANDLER_DCCENABLENFC_BASE = 1 AND COALESCE(HANDLER_DCCENABLENFC_CHECK_O, 1) = 1)
           OR (HANDLER_DCCENABLENFCSINGLETAP_BASE = 1 AND COALESCE(HANDLER_DCCENABLENFCSINGLETAP_CHECK_O, 1) = 1)
           OR (DCCFLAGSENABLED_BASE = 1 AND COALESCE(DCCFLAGSENABLED_CHECK_C, 1) = 1)
           OR (DCCXPRESSCO_BASE = 1 AND COALESCE(DCCXPRESSCO_CHECK_O, 1) = 1)
           OR (DCCXPRESSCODT_BASE = 1 AND COALESCE(DCCXPRESSCODT_CHECK_O, 1) = 1)
           OR (DCCXPRESSCOFALLBACK_BASE = 1 AND COALESCE(DCCXPRESSCOFALLBACK_CHECK_O, 1) = 1)
           OR (DCCMERCHANT_NO_BASE = 1 AND COALESCE(DCCMERCHANT_NO_CHECK_O, 1) = 1)
           OR (FIRMWARE_VERSION_BASE = 1 AND COALESCE(FIRMWARE_VERSION_CHECK, 1) = 1)
           OR (PRINTOUTTYPETEMPLATEDCC_BASE = 1 AND COALESCE(PRINTOUTTYPETEMPLATEDCC_CHECK_C, 1) = 1)
           OR (CONFIGDOWNLOAD_VERSION_CHECK_BASE = 1 AND COALESCE(CONFIGDOWNLOAD_VERSION_CHECK_C, 1) = 1)
      )
    GROUP BY TERMINAL_IDENTIFIER
) src
ON tgt.SNAPSHOT_DATE = src.SNAPSHOT_DATE AND tgt.TERMINAL_IDENTIFIER = src.TERMINAL_IDENTIFIER
WHEN MATCHED THEN UPDATE SET
    INSTANCE_IDENTIFIER = src.INSTANCE_IDENTIFIER,
    LOCATION_NO = src.LOCATION_NO,
    COUNTRY_NAME = src.COUNTRY_NAME,
    REGION = src.REGION,
    INDUSTRY_NAME = src.INDUSTRY_NAME,
    BANK_MERCHANT_ID = src.BANK_MERCHANT_ID,
    MERCHANT_NAME = src.MERCHANT_NAME,
    CUSTOMER_NAME = src.CUSTOMER_NAME,
    ACQUIRER_NAME = src.ACQUIRER_NAME,
    LOCATION_NAME = src.LOCATION_NAME,
    TERMINAL_BRAND_NAME = src.TERMINAL_BRAND_NAME,
    TERMINAL_MODEL_NAME = src.TERMINAL_MODEL_NAME,
    FIRMWARE_VERSION = src.FIRMWARE_VERSION,
    LOCATION_DCCENABLED_CHECK_C = src.LOCATION_DCCENABLED_CHECK_C,
    HANDLER_DCCENABLE_CHECK_O = src.HANDLER_DCCENABLE_CHECK_O,
    HANDLER_DCCENABLECOMPLETION_CHECK_O = src.HANDLER_DCCENABLECOMPLETION_CHECK_O,
    HANDLER_DCCENABLEAUTH_CHECK_O = src.HANDLER_DCCENABLEAUTH_CHECK_O,
    HANDLER_DCCENABLENFC_CHECK_O = src.HANDLER_DCCENABLENFC_CHECK_O,
    HANDLER_DCCENABLENFCSINGLETAP_CHECK_O = src.HANDLER_DCCENABLENFCSINGLETAP_CHECK_O,
    DCCFLAGSENABLED_CHECK_C = src.DCCFLAGSENABLED_CHECK_C,
    DCCXPRESSCO_CHECK_O = src.DCCXPRESSCO_CHECK_O,
    DCCXPRESSCODT_CHECK_O = src.DCCXPRESSCODT_CHECK_O,
    DCCXPRESSCOFALLBACK_CHECK_O = src.DCCXPRESSCOFALLBACK_CHECK_O,
    DCCMERCHANT_NO_CHECK_O = src.DCCMERCHANT_NO_CHECK_O,
    FIRMWARE_VERSION_CHECK = src.FIRMWARE_VERSION_CHECK,
    PRINTOUTTYPETEMPLATEDCC_CHECK_C = src.PRINTOUTTYPETEMPLATEDCC_CHECK_C,
    CONFIGDOWNLOAD_VERSION_CHECK_C = src.CONFIGDOWNLOAD_VERSION_CHECK_C,
    IS_DCC_BROKEN = TRUE,
    SOURCE_LAST_ALTERED = src.SOURCE_LAST_ALTERED,
    CAPTURED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (SNAPSHOT_DATE, TERMINAL_IDENTIFIER, INSTANCE_IDENTIFIER, LOCATION_NO, COUNTRY_NAME, REGION, INDUSTRY_NAME, BANK_MERCHANT_ID, MERCHANT_NAME, CUSTOMER_NAME, ACQUIRER_NAME, LOCATION_NAME, TERMINAL_BRAND_NAME, TERMINAL_MODEL_NAME, FIRMWARE_VERSION, LOCATION_DCCENABLED_CHECK_C, HANDLER_DCCENABLE_CHECK_O, HANDLER_DCCENABLECOMPLETION_CHECK_O, HANDLER_DCCENABLEAUTH_CHECK_O, HANDLER_DCCENABLENFC_CHECK_O, HANDLER_DCCENABLENFCSINGLETAP_CHECK_O, DCCFLAGSENABLED_CHECK_C, DCCXPRESSCO_CHECK_O, DCCXPRESSCODT_CHECK_O, DCCXPRESSCOFALLBACK_CHECK_O, DCCMERCHANT_NO_CHECK_O, FIRMWARE_VERSION_CHECK, PRINTOUTTYPETEMPLATEDCC_CHECK_C, CONFIGDOWNLOAD_VERSION_CHECK_C, IS_DCC_BROKEN, SOURCE_LAST_ALTERED)
VALUES (src.SNAPSHOT_DATE, src.TERMINAL_IDENTIFIER, src.INSTANCE_IDENTIFIER, src.LOCATION_NO, src.COUNTRY_NAME, src.REGION, src.INDUSTRY_NAME, src.BANK_MERCHANT_ID, src.MERCHANT_NAME, src.CUSTOMER_NAME, src.ACQUIRER_NAME, src.LOCATION_NAME, src.TERMINAL_BRAND_NAME, src.TERMINAL_MODEL_NAME, src.FIRMWARE_VERSION, src.LOCATION_DCCENABLED_CHECK_C, src.HANDLER_DCCENABLE_CHECK_O, src.HANDLER_DCCENABLECOMPLETION_CHECK_O, src.HANDLER_DCCENABLEAUTH_CHECK_O, src.HANDLER_DCCENABLENFC_CHECK_O, src.HANDLER_DCCENABLENFCSINGLETAP_CHECK_O, src.DCCFLAGSENABLED_CHECK_C, src.DCCXPRESSCO_CHECK_O, src.DCCXPRESSCODT_CHECK_O, src.DCCXPRESSCOFALLBACK_CHECK_O, src.DCCMERCHANT_NO_CHECK_O, src.FIRMWARE_VERSION_CHECK, src.PRINTOUTTYPETEMPLATEDCC_CHECK_C, src.CONFIGDOWNLOAD_VERSION_CHECK_C, TRUE, src.SOURCE_LAST_ALTERED)
