-- =====================================================================
-- Confirm fixes + profit handoff for DEV_CORE_AAB.DCC_REMEDIATION.DCC_CONFIRMED_FIXES
-- GENERATED from src/dcc_console/remediation/reconcile.py (create_confirmed_table / build_reconcile_block / build_reconcile_task).
-- Do not hand-edit; change the builder and regenerate. Idempotent, safe to re-run.
-- The app's "Initialise / verify my schema" button runs exactly these statements
-- for the connected user's own schema (+ the shared fix-log schema).
-- =====================================================================

CREATE TABLE IF NOT EXISTS DEV_CORE_AAB.DCC_REMEDIATION.DCC_CONFIRMED_FIXES (
    ENVIRONMENT          VARCHAR(20)  NOT NULL,
    TERMINAL_IDENTIFIER  VARCHAR(100) NOT NULL,
    CHECK_COLUMN         VARCHAR(80)  NOT NULL,
    FLAG_NAME            VARCHAR(120),
    FIX_BIT              NUMBER(4,0),
    VALUE_SENT           VARCHAR(120),
    TARGET_ID_KIND       VARCHAR(30),
    TARGET_IDENTIFIER    VARCHAR(100),
    INSTANCE_IDENTIFIER  VARCHAR(100),
    LOCATION_NO          VARCHAR(50),
    CORRELATION_ID       VARCHAR(64),
    CHANGE_REF           VARCHAR(120),
    RESOLUTION           VARCHAR(20),
    FIXED_BY             VARCHAR(150),
    FIXED_AT_UTC         TIMESTAMP_NTZ NOT NULL,
    SRC_LOADED_UTC       TIMESTAMP_NTZ,
    CONFIRMED_AT_UTC     TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    COUNTRY_NAME         VARCHAR(100),
    REGION               VARCHAR(100),
    INDUSTRY_NAME        VARCHAR(100),
    BANK_MERCHANT_ID     VARCHAR(50),
    MERCHANT_NAME        VARCHAR(250),
    CUSTOMER_NAME        VARCHAR(250),
    ACQUIRER_NAME        VARCHAR(250),
    LOCATION_NAME        VARCHAR(500),
    TERMINAL_BRAND_NAME  VARCHAR(100),
    TERMINAL_MODEL_NAME  VARCHAR(200),
    FIRMWARE_VERSION     VARCHAR(200),
    PRIMARY KEY (ENVIRONMENT, TERMINAL_IDENTIFIER, CHECK_COLUMN, FIXED_AT_UTC)
);

-- Confirm fixes vs Cortex and hand them to the profit table (run by the app button).
EXECUTE IMMEDIATE $$
BEGIN
    BEGIN TRANSACTION;
    MERGE INTO DEV_CORE_AAB.DCC_REMEDIATION.DCC_CONFIRMED_FIXES tgt
USING (
    WITH cortex AS (
        SELECT TERMINAL_IDENTIFIER,
           MAX(COUNTRY_NAME) AS COUNTRY_NAME,
           MAX(REGION) AS REGION,
           MAX(INDUSTRY_NAME) AS INDUSTRY_NAME,
           MAX(BANK_MERCHANT_ID) AS BANK_MERCHANT_ID,
           MAX(MERCHANT_NAME) AS MERCHANT_NAME,
           MAX(CUSTOMER_NAME) AS CUSTOMER_NAME,
           MAX(ACQUIRER_NAME) AS ACQUIRER_NAME,
           MAX(LOCATION_NAME) AS LOCATION_NAME,
           MAX(TERMINAL_BRAND_NAME) AS TERMINAL_BRAND_NAME,
           MAX(TERMINAL_MODEL_NAME) AS TERMINAL_MODEL_NAME,
           MAX(FIRMWARE_VERSION) AS FIRMWARE_VERSION,
           MAX(IFF(LOCATION_DCCENABLED_BASE = 1 AND COALESCE(LOCATION_DCCENABLED_CHECK_C, 1) = 1, 1, 0)) AS LOCATION_DCCENABLED_CHECK_C,
           MAX(IFF(HANDLER_DCCENABLE_BASE = 1 AND COALESCE(HANDLER_DCCENABLE_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLE_CHECK_O,
           MAX(IFF(HANDLER_DCCENABLECOMPLETION_BASE = 1 AND COALESCE(HANDLER_DCCENABLECOMPLETION_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLECOMPLETION_CHECK_O,
           MAX(IFF(HANDLER_DCCENABLEAUTH_BASE = 1 AND COALESCE(HANDLER_DCCENABLEAUTH_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLEAUTH_CHECK_O,
           MAX(IFF(HANDLER_DCCENABLENFC_BASE = 1 AND COALESCE(HANDLER_DCCENABLENFC_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLENFC_CHECK_O,
           MAX(IFF(HANDLER_DCCENABLENFCSINGLETAP_BASE = 1 AND COALESCE(HANDLER_DCCENABLENFCSINGLETAP_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLENFCSINGLETAP_CHECK_O,
           MAX(IFF(DCCFLAGSENABLED_BASE = 1 AND COALESCE(DCCFLAGSENABLED_CHECK_C, 1) = 1, 1, 0)) AS DCCFLAGSENABLED_CHECK_C,
           MAX(IFF(DCCXPRESSCO_BASE = 1 AND COALESCE(DCCXPRESSCO_CHECK_O, 1) = 1, 1, 0)) AS DCCXPRESSCO_CHECK_O,
           MAX(IFF(DCCXPRESSCODT_BASE = 1 AND COALESCE(DCCXPRESSCODT_CHECK_O, 1) = 1, 1, 0)) AS DCCXPRESSCODT_CHECK_O,
           MAX(IFF(DCCXPRESSCOFALLBACK_BASE = 1 AND COALESCE(DCCXPRESSCOFALLBACK_CHECK_O, 1) = 1, 1, 0)) AS DCCXPRESSCOFALLBACK_CHECK_O,
           MAX(IFF(DCCMERCHANT_NO_BASE = 1 AND COALESCE(DCCMERCHANT_NO_CHECK_O, 1) = 1, 1, 0)) AS DCCMERCHANT_NO_CHECK_O,
           MAX(IFF(FIRMWARE_VERSION_BASE = 1 AND COALESCE(FIRMWARE_VERSION_CHECK, 1) = 1, 1, 0)) AS FIRMWARE_VERSION_CHECK,
           MAX(IFF(PRINTOUTTYPETEMPLATEDCC_BASE = 1 AND COALESCE(PRINTOUTTYPETEMPLATEDCC_CHECK_C, 1) = 1, 1, 0)) AS PRINTOUTTYPETEMPLATEDCC_CHECK_C,
           MAX(IFF(CONFIGDOWNLOAD_VERSION_CHECK_BASE = 1 AND COALESCE(CONFIGDOWNLOAD_VERSION_CHECK_C, 1) = 1, 1, 0)) AS CONFIGDOWNLOAD_VERSION_CHECK_C,
           (SELECT CONVERT_TIMEZONE('UTC', LAST_ALTERED)::TIMESTAMP_NTZ FROM PROD_PRESENTATION.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='CORTEX' AND TABLE_NAME='CORTEX_TERMINAL_MAINTENANCE') AS SRC_LOADED_UTC
        FROM PROD_PRESENTATION.CORTEX.CORTEX_TERMINAL_MAINTENANCE
        WHERE TERMINAL_IDENTIFIER IN (
            SELECT TERMINAL_IDENTIFIER FROM DEV_CORE_AAB.DCC_REMEDIATION.DCC_FIX_REGISTRY
            WHERE ENVIRONMENT = 'PROD' AND STATUS = 'FIXED'
        )
        GROUP BY TERMINAL_IDENTIFIER
    )
    SELECT r.ENVIRONMENT,
               r.TERMINAL_IDENTIFIER,
               r.CHECK_COLUMN,
               r.FLAG_NAME,
               r.FIX_BIT,
               r.VALUE_SENT,
               r.TARGET_ID_KIND,
               r.TARGET_IDENTIFIER,
               r.INSTANCE_IDENTIFIER,
               r.LOCATION_NO,
               r.CORRELATION_ID,
               r.CHANGE_REF,
               r.RESOLUTION,
               r.FIXED_BY,
               r.FIXED_AT_UTC,
               c.SRC_LOADED_UTC,
               CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS CONFIRMED_AT_UTC,
               c.COUNTRY_NAME,
               c.REGION,
               c.INDUSTRY_NAME,
               c.BANK_MERCHANT_ID,
               c.MERCHANT_NAME,
               c.CUSTOMER_NAME,
               c.ACQUIRER_NAME,
               c.LOCATION_NAME,
               c.TERMINAL_BRAND_NAME,
               c.TERMINAL_MODEL_NAME,
               c.FIRMWARE_VERSION
    FROM DEV_CORE_AAB.DCC_REMEDIATION.DCC_FIX_REGISTRY r
    JOIN cortex c ON c.TERMINAL_IDENTIFIER = r.TERMINAL_IDENTIFIER
    WHERE r.ENVIRONMENT = 'PROD' AND r.STATUS = 'FIXED'
      AND c.SRC_LOADED_UTC > r.FIXED_AT_UTC
      AND (CASE r.CHECK_COLUMN
                WHEN 'LOCATION_DCCENABLED_CHECK_C' THEN c.LOCATION_DCCENABLED_CHECK_C
                WHEN 'HANDLER_DCCENABLE_CHECK_O' THEN c.HANDLER_DCCENABLE_CHECK_O
                WHEN 'HANDLER_DCCENABLECOMPLETION_CHECK_O' THEN c.HANDLER_DCCENABLECOMPLETION_CHECK_O
                WHEN 'HANDLER_DCCENABLEAUTH_CHECK_O' THEN c.HANDLER_DCCENABLEAUTH_CHECK_O
                WHEN 'HANDLER_DCCENABLENFC_CHECK_O' THEN c.HANDLER_DCCENABLENFC_CHECK_O
                WHEN 'HANDLER_DCCENABLENFCSINGLETAP_CHECK_O' THEN c.HANDLER_DCCENABLENFCSINGLETAP_CHECK_O
                WHEN 'DCCFLAGSENABLED_CHECK_C' THEN c.DCCFLAGSENABLED_CHECK_C
                WHEN 'DCCXPRESSCO_CHECK_O' THEN c.DCCXPRESSCO_CHECK_O
                WHEN 'DCCXPRESSCODT_CHECK_O' THEN c.DCCXPRESSCODT_CHECK_O
                WHEN 'DCCXPRESSCOFALLBACK_CHECK_O' THEN c.DCCXPRESSCOFALLBACK_CHECK_O
                WHEN 'DCCMERCHANT_NO_CHECK_O' THEN c.DCCMERCHANT_NO_CHECK_O
                WHEN 'FIRMWARE_VERSION_CHECK' THEN c.FIRMWARE_VERSION_CHECK
                WHEN 'PRINTOUTTYPETEMPLATEDCC_CHECK_C' THEN c.PRINTOUTTYPETEMPLATEDCC_CHECK_C
                WHEN 'CONFIGDOWNLOAD_VERSION_CHECK_C' THEN c.CONFIGDOWNLOAD_VERSION_CHECK_C
                ELSE 1
            END) = 0
) src
ON tgt.ENVIRONMENT = src.ENVIRONMENT
   AND tgt.TERMINAL_IDENTIFIER = src.TERMINAL_IDENTIFIER
   AND tgt.CHECK_COLUMN = src.CHECK_COLUMN
   AND tgt.FIXED_AT_UTC = src.FIXED_AT_UTC
WHEN NOT MATCHED THEN INSERT (ENVIRONMENT, TERMINAL_IDENTIFIER, CHECK_COLUMN, FLAG_NAME, FIX_BIT, VALUE_SENT, TARGET_ID_KIND, TARGET_IDENTIFIER, INSTANCE_IDENTIFIER, LOCATION_NO, CORRELATION_ID, CHANGE_REF, RESOLUTION, FIXED_BY, FIXED_AT_UTC, SRC_LOADED_UTC, CONFIRMED_AT_UTC, COUNTRY_NAME, REGION, INDUSTRY_NAME, BANK_MERCHANT_ID, MERCHANT_NAME, CUSTOMER_NAME, ACQUIRER_NAME, LOCATION_NAME, TERMINAL_BRAND_NAME, TERMINAL_MODEL_NAME, FIRMWARE_VERSION)
VALUES (src.ENVIRONMENT, src.TERMINAL_IDENTIFIER, src.CHECK_COLUMN, src.FLAG_NAME, src.FIX_BIT, src.VALUE_SENT, src.TARGET_ID_KIND, src.TARGET_IDENTIFIER, src.INSTANCE_IDENTIFIER, src.LOCATION_NO, src.CORRELATION_ID, src.CHANGE_REF, src.RESOLUTION, src.FIXED_BY, src.FIXED_AT_UTC, src.SRC_LOADED_UTC, src.CONFIRMED_AT_UTC, src.COUNTRY_NAME, src.REGION, src.INDUSTRY_NAME, src.BANK_MERCHANT_ID, src.MERCHANT_NAME, src.CUSTOMER_NAME, src.ACQUIRER_NAME, src.LOCATION_NAME, src.TERMINAL_BRAND_NAME, src.TERMINAL_MODEL_NAME, src.FIRMWARE_VERSION);
    UPDATE DEV_CORE_AAB.DCC_REMEDIATION.DCC_FIX_REGISTRY r
SET STATUS = 'CONFIRMED',
    CONFIRMED_AT_UTC = (
        SELECT MAX(h.CONFIRMED_AT_UTC) FROM DEV_CORE_AAB.DCC_REMEDIATION.DCC_CONFIRMED_FIXES h
        WHERE h.ENVIRONMENT = r.ENVIRONMENT
          AND h.TERMINAL_IDENTIFIER = r.TERMINAL_IDENTIFIER
          AND h.CHECK_COLUMN = r.CHECK_COLUMN
          AND h.FIXED_AT_UTC = r.FIXED_AT_UTC
    )
WHERE r.ENVIRONMENT = 'PROD' AND r.STATUS = 'FIXED'
  AND EXISTS (
        SELECT 1 FROM DEV_CORE_AAB.DCC_REMEDIATION.DCC_CONFIRMED_FIXES h
        WHERE h.ENVIRONMENT = r.ENVIRONMENT
          AND h.TERMINAL_IDENTIFIER = r.TERMINAL_IDENTIFIER
          AND h.CHECK_COLUMN = r.CHECK_COLUMN
          AND h.FIXED_AT_UTC = r.FIXED_AT_UTC
  );
    COMMIT;
    RETURN 'reconciled';
END;
$$;

-- Optional daily automation. Needs EXECUTE TASK on the account for the task owner
-- and SELECT on the Cortex source; see docs/plan_dcc_remediation.md runbook.
CREATE TASK IF NOT EXISTS DEV_CORE_AAB.DCC_REMEDIATION.DCC_RECONCILE_CONFIRMED_FIXES_TASK
    WAREHOUSE = DATA_SCIENCE
    SCHEDULE = 'USING CRON 30 6 * * * UTC'
AS
BEGIN
    BEGIN TRANSACTION;
    MERGE INTO DEV_CORE_AAB.DCC_REMEDIATION.DCC_CONFIRMED_FIXES tgt
USING (
    WITH cortex AS (
        SELECT TERMINAL_IDENTIFIER,
           MAX(COUNTRY_NAME) AS COUNTRY_NAME,
           MAX(REGION) AS REGION,
           MAX(INDUSTRY_NAME) AS INDUSTRY_NAME,
           MAX(BANK_MERCHANT_ID) AS BANK_MERCHANT_ID,
           MAX(MERCHANT_NAME) AS MERCHANT_NAME,
           MAX(CUSTOMER_NAME) AS CUSTOMER_NAME,
           MAX(ACQUIRER_NAME) AS ACQUIRER_NAME,
           MAX(LOCATION_NAME) AS LOCATION_NAME,
           MAX(TERMINAL_BRAND_NAME) AS TERMINAL_BRAND_NAME,
           MAX(TERMINAL_MODEL_NAME) AS TERMINAL_MODEL_NAME,
           MAX(FIRMWARE_VERSION) AS FIRMWARE_VERSION,
           MAX(IFF(LOCATION_DCCENABLED_BASE = 1 AND COALESCE(LOCATION_DCCENABLED_CHECK_C, 1) = 1, 1, 0)) AS LOCATION_DCCENABLED_CHECK_C,
           MAX(IFF(HANDLER_DCCENABLE_BASE = 1 AND COALESCE(HANDLER_DCCENABLE_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLE_CHECK_O,
           MAX(IFF(HANDLER_DCCENABLECOMPLETION_BASE = 1 AND COALESCE(HANDLER_DCCENABLECOMPLETION_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLECOMPLETION_CHECK_O,
           MAX(IFF(HANDLER_DCCENABLEAUTH_BASE = 1 AND COALESCE(HANDLER_DCCENABLEAUTH_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLEAUTH_CHECK_O,
           MAX(IFF(HANDLER_DCCENABLENFC_BASE = 1 AND COALESCE(HANDLER_DCCENABLENFC_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLENFC_CHECK_O,
           MAX(IFF(HANDLER_DCCENABLENFCSINGLETAP_BASE = 1 AND COALESCE(HANDLER_DCCENABLENFCSINGLETAP_CHECK_O, 1) = 1, 1, 0)) AS HANDLER_DCCENABLENFCSINGLETAP_CHECK_O,
           MAX(IFF(DCCFLAGSENABLED_BASE = 1 AND COALESCE(DCCFLAGSENABLED_CHECK_C, 1) = 1, 1, 0)) AS DCCFLAGSENABLED_CHECK_C,
           MAX(IFF(DCCXPRESSCO_BASE = 1 AND COALESCE(DCCXPRESSCO_CHECK_O, 1) = 1, 1, 0)) AS DCCXPRESSCO_CHECK_O,
           MAX(IFF(DCCXPRESSCODT_BASE = 1 AND COALESCE(DCCXPRESSCODT_CHECK_O, 1) = 1, 1, 0)) AS DCCXPRESSCODT_CHECK_O,
           MAX(IFF(DCCXPRESSCOFALLBACK_BASE = 1 AND COALESCE(DCCXPRESSCOFALLBACK_CHECK_O, 1) = 1, 1, 0)) AS DCCXPRESSCOFALLBACK_CHECK_O,
           MAX(IFF(DCCMERCHANT_NO_BASE = 1 AND COALESCE(DCCMERCHANT_NO_CHECK_O, 1) = 1, 1, 0)) AS DCCMERCHANT_NO_CHECK_O,
           MAX(IFF(FIRMWARE_VERSION_BASE = 1 AND COALESCE(FIRMWARE_VERSION_CHECK, 1) = 1, 1, 0)) AS FIRMWARE_VERSION_CHECK,
           MAX(IFF(PRINTOUTTYPETEMPLATEDCC_BASE = 1 AND COALESCE(PRINTOUTTYPETEMPLATEDCC_CHECK_C, 1) = 1, 1, 0)) AS PRINTOUTTYPETEMPLATEDCC_CHECK_C,
           MAX(IFF(CONFIGDOWNLOAD_VERSION_CHECK_BASE = 1 AND COALESCE(CONFIGDOWNLOAD_VERSION_CHECK_C, 1) = 1, 1, 0)) AS CONFIGDOWNLOAD_VERSION_CHECK_C,
           (SELECT CONVERT_TIMEZONE('UTC', LAST_ALTERED)::TIMESTAMP_NTZ FROM PROD_PRESENTATION.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='CORTEX' AND TABLE_NAME='CORTEX_TERMINAL_MAINTENANCE') AS SRC_LOADED_UTC
        FROM PROD_PRESENTATION.CORTEX.CORTEX_TERMINAL_MAINTENANCE
        WHERE TERMINAL_IDENTIFIER IN (
            SELECT TERMINAL_IDENTIFIER FROM DEV_CORE_AAB.DCC_REMEDIATION.DCC_FIX_REGISTRY
            WHERE ENVIRONMENT = 'PROD' AND STATUS = 'FIXED'
        )
        GROUP BY TERMINAL_IDENTIFIER
    )
    SELECT r.ENVIRONMENT,
               r.TERMINAL_IDENTIFIER,
               r.CHECK_COLUMN,
               r.FLAG_NAME,
               r.FIX_BIT,
               r.VALUE_SENT,
               r.TARGET_ID_KIND,
               r.TARGET_IDENTIFIER,
               r.INSTANCE_IDENTIFIER,
               r.LOCATION_NO,
               r.CORRELATION_ID,
               r.CHANGE_REF,
               r.RESOLUTION,
               r.FIXED_BY,
               r.FIXED_AT_UTC,
               c.SRC_LOADED_UTC,
               CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS CONFIRMED_AT_UTC,
               c.COUNTRY_NAME,
               c.REGION,
               c.INDUSTRY_NAME,
               c.BANK_MERCHANT_ID,
               c.MERCHANT_NAME,
               c.CUSTOMER_NAME,
               c.ACQUIRER_NAME,
               c.LOCATION_NAME,
               c.TERMINAL_BRAND_NAME,
               c.TERMINAL_MODEL_NAME,
               c.FIRMWARE_VERSION
    FROM DEV_CORE_AAB.DCC_REMEDIATION.DCC_FIX_REGISTRY r
    JOIN cortex c ON c.TERMINAL_IDENTIFIER = r.TERMINAL_IDENTIFIER
    WHERE r.ENVIRONMENT = 'PROD' AND r.STATUS = 'FIXED'
      AND c.SRC_LOADED_UTC > r.FIXED_AT_UTC
      AND (CASE r.CHECK_COLUMN
                WHEN 'LOCATION_DCCENABLED_CHECK_C' THEN c.LOCATION_DCCENABLED_CHECK_C
                WHEN 'HANDLER_DCCENABLE_CHECK_O' THEN c.HANDLER_DCCENABLE_CHECK_O
                WHEN 'HANDLER_DCCENABLECOMPLETION_CHECK_O' THEN c.HANDLER_DCCENABLECOMPLETION_CHECK_O
                WHEN 'HANDLER_DCCENABLEAUTH_CHECK_O' THEN c.HANDLER_DCCENABLEAUTH_CHECK_O
                WHEN 'HANDLER_DCCENABLENFC_CHECK_O' THEN c.HANDLER_DCCENABLENFC_CHECK_O
                WHEN 'HANDLER_DCCENABLENFCSINGLETAP_CHECK_O' THEN c.HANDLER_DCCENABLENFCSINGLETAP_CHECK_O
                WHEN 'DCCFLAGSENABLED_CHECK_C' THEN c.DCCFLAGSENABLED_CHECK_C
                WHEN 'DCCXPRESSCO_CHECK_O' THEN c.DCCXPRESSCO_CHECK_O
                WHEN 'DCCXPRESSCODT_CHECK_O' THEN c.DCCXPRESSCODT_CHECK_O
                WHEN 'DCCXPRESSCOFALLBACK_CHECK_O' THEN c.DCCXPRESSCOFALLBACK_CHECK_O
                WHEN 'DCCMERCHANT_NO_CHECK_O' THEN c.DCCMERCHANT_NO_CHECK_O
                WHEN 'FIRMWARE_VERSION_CHECK' THEN c.FIRMWARE_VERSION_CHECK
                WHEN 'PRINTOUTTYPETEMPLATEDCC_CHECK_C' THEN c.PRINTOUTTYPETEMPLATEDCC_CHECK_C
                WHEN 'CONFIGDOWNLOAD_VERSION_CHECK_C' THEN c.CONFIGDOWNLOAD_VERSION_CHECK_C
                ELSE 1
            END) = 0
) src
ON tgt.ENVIRONMENT = src.ENVIRONMENT
   AND tgt.TERMINAL_IDENTIFIER = src.TERMINAL_IDENTIFIER
   AND tgt.CHECK_COLUMN = src.CHECK_COLUMN
   AND tgt.FIXED_AT_UTC = src.FIXED_AT_UTC
WHEN NOT MATCHED THEN INSERT (ENVIRONMENT, TERMINAL_IDENTIFIER, CHECK_COLUMN, FLAG_NAME, FIX_BIT, VALUE_SENT, TARGET_ID_KIND, TARGET_IDENTIFIER, INSTANCE_IDENTIFIER, LOCATION_NO, CORRELATION_ID, CHANGE_REF, RESOLUTION, FIXED_BY, FIXED_AT_UTC, SRC_LOADED_UTC, CONFIRMED_AT_UTC, COUNTRY_NAME, REGION, INDUSTRY_NAME, BANK_MERCHANT_ID, MERCHANT_NAME, CUSTOMER_NAME, ACQUIRER_NAME, LOCATION_NAME, TERMINAL_BRAND_NAME, TERMINAL_MODEL_NAME, FIRMWARE_VERSION)
VALUES (src.ENVIRONMENT, src.TERMINAL_IDENTIFIER, src.CHECK_COLUMN, src.FLAG_NAME, src.FIX_BIT, src.VALUE_SENT, src.TARGET_ID_KIND, src.TARGET_IDENTIFIER, src.INSTANCE_IDENTIFIER, src.LOCATION_NO, src.CORRELATION_ID, src.CHANGE_REF, src.RESOLUTION, src.FIXED_BY, src.FIXED_AT_UTC, src.SRC_LOADED_UTC, src.CONFIRMED_AT_UTC, src.COUNTRY_NAME, src.REGION, src.INDUSTRY_NAME, src.BANK_MERCHANT_ID, src.MERCHANT_NAME, src.CUSTOMER_NAME, src.ACQUIRER_NAME, src.LOCATION_NAME, src.TERMINAL_BRAND_NAME, src.TERMINAL_MODEL_NAME, src.FIRMWARE_VERSION);
    UPDATE DEV_CORE_AAB.DCC_REMEDIATION.DCC_FIX_REGISTRY r
SET STATUS = 'CONFIRMED',
    CONFIRMED_AT_UTC = (
        SELECT MAX(h.CONFIRMED_AT_UTC) FROM DEV_CORE_AAB.DCC_REMEDIATION.DCC_CONFIRMED_FIXES h
        WHERE h.ENVIRONMENT = r.ENVIRONMENT
          AND h.TERMINAL_IDENTIFIER = r.TERMINAL_IDENTIFIER
          AND h.CHECK_COLUMN = r.CHECK_COLUMN
          AND h.FIXED_AT_UTC = r.FIXED_AT_UTC
    )
WHERE r.ENVIRONMENT = 'PROD' AND r.STATUS = 'FIXED'
  AND EXISTS (
        SELECT 1 FROM DEV_CORE_AAB.DCC_REMEDIATION.DCC_CONFIRMED_FIXES h
        WHERE h.ENVIRONMENT = r.ENVIRONMENT
          AND h.TERMINAL_IDENTIFIER = r.TERMINAL_IDENTIFIER
          AND h.CHECK_COLUMN = r.CHECK_COLUMN
          AND h.FIXED_AT_UTC = r.FIXED_AT_UTC
  );
    COMMIT;
    RETURN 'reconciled';
END;

ALTER TASK IF EXISTS DEV_CORE_AAB.DCC_REMEDIATION.DCC_RECONCILE_CONFIRMED_FIXES_TASK RESUME;
